# Generated by Django 4.1.4 on 2022-12-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='contentone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='creative',
            field=models.TextField(blank=True, null=True),
        ),
    ]
