# Generated by Django 4.1.4 on 2022-12-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_contentone_blog_creative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='contentone',
            new_name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='content_continued',
            field=models.TextField(blank=True, null=True),
        ),
    ]
