# Generated by Django 4.1.4 on 2022-12-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=202)),
                ('start_finish', models.CharField(max_length=202)),
                ('address', models.CharField(max_length=303)),
                ('text', models.CharField(max_length=505)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=202)),
                ('start_finish', models.CharField(max_length=202)),
                ('address', models.CharField(max_length=303)),
                ('text', models.CharField(max_length=505)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=202)),
                ('start_finish', models.CharField(max_length=202)),
                ('address', models.CharField(max_length=303)),
                ('text', models.CharField(max_length=505)),
            ],
        ),
    ]
