# Generated by Django 4.1.4 on 2022-12-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=202)),
                ('start_finish', models.CharField(max_length=202)),
                ('address', models.CharField(max_length=303)),
                ('text', models.CharField(max_length=505)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=202)),
                ('start_finish', models.CharField(max_length=202)),
                ('address', models.CharField(max_length=303)),
                ('text', models.CharField(max_length=505)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=202)),
                ('start_finish', models.CharField(max_length=202)),
                ('address', models.CharField(max_length=303)),
                ('text', models.CharField(max_length=505)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=202, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('last_week', models.IntegerField(blank=True, null=True)),
                ('last_month', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=202, null=True)),
                ('foiz', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
